Add files via upload
DariaGorbach/iterate_generate pull request #1
Opened 2019-02-27 14:06 UTC by DariaGorbach

2019-03-05 08:11 UTC, AleksandrSl commented on gen_test.py
> +            next(test_generation)
Внутри одного `assertRaises` бессмысленно, так как если первый `next(test_generation)` выкинет тебе ошибку, тест все равно пройдет успешно, в `assertRaises` должно быть единственное по возможности выражение или statement, которое кидает ошибку

2019-03-05 08:11 UTC, AleksandrSl commented on iter_test.py
> +class IterTest(unittest.TestCase):
Так как тестируем мы в данном случае один и тот же "интерфейс" итератора, то можно не дублировать код тестов, просто заменить `MyIterator` на `MyGenerator.my_range`

2019-03-06 08:49 UTC, AleksandrSl commented on iter_gen.py
> +        step = 1
Эта строчка ни на что не влияет. значения по умолчанию надо писать прямо в `__init__`

2019-03-09 12:56 UTC, AleksandrSl requested changes

2019-03-09 12:56 UTC, AleksandrSl commented on iter_gen.py
> +    def __init__(self, start, stop, step = 1):
По PEP-8 одна строка должна быть между методами в классе

2019-03-09 12:56 UTC, AleksandrSl commented on iter_gen.py
> +            current_num = self.start
Эта строчка дублирует 21

2019-03-09 12:56 UTC, AleksandrSl commented on iter_gen.py
> +            current_num = self.start
И лучше вообще делать так 
```
if self.current_num >= self.stop:
    raise StopIteration          
self.current_num += self.step
return self.current_num
```
и в конструкторе сделать 
```
self.current_num = self.start
```
Так как в твоем случае нет особого смысла от переменной `current_num`, а вот менять `self.start` не очень хорошо, так как имя переменной перестает отражать ее содержимое

2019-03-09 12:56 UTC, AleksandrSl commented on iter_gen.py
> +class MyGenerator:
В класс функцию генератор можно было не заворачивать - это бессмымленно, разве что сделать этот класс оберткой в которой в функции `__iter__` возвращать результат вызова функции генератора.

```
def __iter__(self):
    return self.my_range(self.start, self.stop, self.step)
```
Ну и конструткор класса при этом придется расширить

2019-03-11 12:42 UTC, closed without merging

2019-03-11 12:44 UTC, DariaGorbach commented
Так как у меня все еще проблемы с кодировками, и я не могу клонировать и коммитить с локального гита, я закрою этот пул реквест и загружу исправленный код снова. Надеюсь, это не очень плохо (я знаю, что плохо).